version: "3"

services:
  server:
    image: my-node:latest
    expose:
      - 3000
    ports:
      - "3001:3000"
    links:
      - mongodb
      - redis
  redis:
    image: redis:latest
    expose:
      - 6379
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:latest
    volumes:
      - ./db:/data/db
    expose:
      - 27017
    ports:
      - "27017:27017"